# Generated by Django 5.1.6 on 2025-02-25 07:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myneo4j', '0002_mywenda'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mywenda',
            options={'ordering': ['-created_at'], 'verbose_name': '问答信息', 'verbose_name_plural': '问答信息'},
        ),
        migrations.RemoveField(
            model_name='mywenda',
            name='anster',
        ),
        migrations.AddField(
            model_name='mywenda',
            name='answer',
            field=models.TextField(default='', verbose_name='答案'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mywenda',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mywenda',
            name='kg_context',
            field=models.TextField(blank=True, null=True, verbose_name='知识图谱上下文'),
        ),
        migrations.AddField(
            model_name='mywenda',
            name='sub_questions',
            field=models.TextField(blank=True, null=True, verbose_name='子问题'),
        ),
        migrations.AlterField(
            model_name='mywenda',
            name='question',
            field=models.TextField(default='', verbose_name='问题'),
            preserve_default=False,
        ),
    ]
