# Generated by Django 5.1.6 on 2025-03-06 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myneo4j', '0003_alter_mywenda_options_remove_mywenda_anster_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mynode',
            options={'verbose_name': '知识图谱节点', 'verbose_name_plural': '知识图谱节点'},
        ),
        migrations.AlterModelOptions(
            name='mywenda',
            options={'ordering': ['-created_at'], 'verbose_name': '问答记录', 'verbose_name_plural': '问答记录'},
        ),
        migrations.RemoveField(
            model_name='mynode',
            name='leixing',
        ),
        migrations.AddField(
            model_name='mynode',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='类别'),
        ),
        migrations.AddField(
            model_name='mynode',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='描述'),
        ),
        migrations.AddField(
            model_name='mywenda',
            name='kg_nodes',
            field=models.TextField(blank=True, null=True, verbose_name='知识图谱节点'),
        ),
        migrations.AddField(
            model_name='mywenda',
            name='sub_answers',
            field=models.TextField(blank=True, null=True, verbose_name='子问题回答'),
        ),
        migrations.AddField(
            model_name='mywenda',
            name='thinking_process',
            field=models.TextField(blank=True, null=True, verbose_name='思考过程'),
        ),
        migrations.AddField(
            model_name='mywenda',
            name='time_analysis',
            field=models.TextField(blank=True, null=True, verbose_name='时间分析'),
        ),
        migrations.AlterField(
            model_name='mynode',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='节点名称'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mywenda',
            name='answer',
            field=models.TextField(verbose_name='回答'),
        ),
        migrations.AlterField(
            model_name='mywenda',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='mywenda',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
