# Generated by Django 5.1.6 on 2025-03-10 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myneo4j', '0004_alter_mynode_options_alter_mywenda_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(help_text='会话标识符', max_length=64)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('question', models.TextField(help_text='用户问题')),
                ('answer', models.TextField(help_text='回答文本')),
                ('kg_nodes', models.TextField(blank=True, help_text='知识图谱节点数据(JSON)', null=True)),
                ('thinking_process', models.TextField(blank=True, help_text='思考过程数据(JSON)', null=True)),
                ('time_analysis', models.TextField(blank=True, help_text='时间分析数据(JSON)', null=True)),
                ('references', models.TextField(blank=True, help_text='参考文献(JSON)', null=True)),
                ('has_flowchart', models.BooleanField(default=False, help_text='是否包含流程图')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
